source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# bundle edge rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# use sqlite3 as the database for active record

gem 'sqlite3'
# use puma as the app server
gem 'puma', '~> 3.0'
# use scss for stylesheets
gem 'sass-rails', '~> 5.0'
# use uglifier as compressor for javascript assets
gem 'uglifier', '>= 1.3.0'
# use coffeescript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# see https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# use jquery as the javascript library
gem 'jquery-rails'
# turbolinks makes navigating your web application faster. read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# build json apis with ease. read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# use redis adapter to run action cable in production
# gem 'redis', '~> 3.0'
# use activemodel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'devise'
# use capistrano for deployment
# gem 'capistrano-rails', group: :development


group :development, :test do
  # call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # access an irb console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # spring speeds up development by keeping your application running in the background. read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
