# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4f6f6369043c1821f08c3c2481caf51e4c1b768c60cb273a156d421cb7315ec19989cd86d3a9500a0f5fba3bfa17433c1d1f7f793741e62a191cc22b478b16

test:
  secret_key_base: 07883ac2fd18b863aea3a784076d8de6c529636cb74cb0bf272895c6800672e0adca85aa3f25d1f0df49ed893e7c3e359e88564d131481a97ecd03c76419c0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
